language: ruby
group: edge

services:
  - redis-server

cache: bundler

env:
  global:
    - PATH=/snap/bin:$PATH

jobs:
  include:
    - stage: "testing time"
      before_install:
        - gem install bundler:2.4.13
        - gem install rubygems-update -v 3.4.22    
      script: bundle exec rspec -f documentation --color --order rand spec
    - stage: ":ship: it to quay.io"
      ruby:
      before_install:
        - gem install bundler:2.4.13
        - gem install rubygems-update -v 3.4.22
      before_script:
      install:
      services:
      cache:
        bundler: false
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
