language: ruby

services:
  - redis-server

cache: bundler

addons:
  snaps:
  - name: docker
    channel: latest/beta

env:
  global:
    - PATH=/snap/bin:$PATH

jobs:
  include:
    - stage: "testing time"
      before_install: sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev && bundle config build.nokogiri --use-system-libraries
      script: bundle exec rspec -f documentation --color --order rand spec
    - stage: ":ship: it to quay.io"
      ruby:
      before_install:
      before_script:
      install:
      services:
      cache:
        bundler: false
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
